name: deploy-main

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.SSH_KEY_PROD }}
      SSH_URL: ${{ vars.SSH_URL_PROD }}  # root@ip
      PROJECT_PATH: "/opt/netrunner-front"
    steps:
      - uses: actions/checkout@v3
      - name: Preparing deploy
        run: |
          echo "Preparing before deploy"
          echo $(dig +short myip.opendns.com @resolver4.opendns.com)
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          touch ~/.ssh/id_rsa
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Deploying
        run: |
          npm install
          CI=false && npm run build
          rsync -za -e "ssh -i ~/.ssh/id_rsa" ./build/* $(echo $SSH_URL):$PROJECT_PATH